---
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended

env:
  node: true
  es6: true
  jest: true
  commonjs: true
  browser: true

parserOptions:
  sourceType: module
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

rules:
  react/prop-types: warn
  react/display-name: off
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
