---
plugins:
  - stylelint-scss
  - stylelint-prettier
extends:
  - stylelint-config-recommended
rules:
  at-rule-no-unknown:
  unit-whitelist:
    - em
    - rem
    - s
    - px
    - vh
    - vw
    - deg
    - '%'
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - export
        - import
        - global
        - local
        - external
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - from
  property-no-unknown:
    - true
    - ignoreProperties:
        - composes
        - compose-with
  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-values
  value-no-vendor-prefix:
  property-no-vendor-prefix:
  selector-no-vendor-prefix:
  media-feature-name-no-vendor-prefix:
  at-rule-no-vendor-prefix:
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - value
  prettier/prettier:
    - true
